// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASsHuYbea4XIsLfZOJMhqO4vWSeivcwdc',
    appId: '1:90266642259:web:3d6039dade81bb290523a6',
    messagingSenderId: '90266642259',
    projectId: 'cloud-view-1',
    authDomain: 'cloud-view-1.firebaseapp.com',
    storageBucket: 'cloud-view-1.appspot.com',
    measurementId: 'G-02KB37LGF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLVzoIYCnHuFgAm9PFuBmfmde_C1V7iyw',
    appId: '1:90266642259:android:d039bcee9333a76c0523a6',
    messagingSenderId: '90266642259',
    projectId: 'cloud-view-1',
    storageBucket: 'cloud-view-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLiFru2FXrz5fxSC6UCC1Clx8mnWge3zU',
    appId: '1:90266642259:ios:79259d808019b7800523a6',
    messagingSenderId: '90266642259',
    projectId: 'cloud-view-1',
    storageBucket: 'cloud-view-1.appspot.com',
    iosBundleId: 'com.example.cloudViewerServies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLiFru2FXrz5fxSC6UCC1Clx8mnWge3zU',
    appId: '1:90266642259:ios:804c53efdcec8cc00523a6',
    messagingSenderId: '90266642259',
    projectId: 'cloud-view-1',
    storageBucket: 'cloud-view-1.appspot.com',
    iosBundleId: 'com.example.cloudViewerServies.RunnerTests',
  );
}
